#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#                ARPABET PHONEME SYMBOLS                    #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

arpa_symbols = {
'AA',
'AA0',
'AA1',
'AA2',
'AE',
'AE0',
'AE1',
'AE2',
'AH',
'AH0',
'AH1',
'AH2',
'AO',
'AO0',
'AO1',
'AO2',
'AW',
'AW0',
'AW1',
'AW2',
'AY',
'AY0',
'AY1',
'AY2',
'B',
'CH',
'D',
'DH',
'EH',
'EH0',
'EH1',
'EH2',
'ER',
'ER0',
'ER1',
'ER2',
'EY',
'EY0',
'EY1',
'EY2',
'F',
'G',
'HH',
'IH',
'IH0',
'IH1',
'IH2',
'IY',
'IY0',
'IY1',
'IY2',
'JH',
'K',
'L',
'M',
'N',
'NG',
'OW',
'OW0',
'OW1',
'OW2',
'OY',
'OY0',
'OY1',
'OY2',
'P',
'R',
'S',
'SH',
'T',
'TH',
'UH',
'UH0',
'UH1',
'UH2',
'UW',
'UW0',
'UW1',
'UW2',
'V',
'W',
'Y',
'Z',
'ZH'
}

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#                ARPABET PHONEME FEATURES                   #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

arpa_features = {
'AA':   ['vowel', 'open', 'back', 'unrounded'],
'AE':   ['vowel', 'near-open', 'front', 'unrounded'],
'AH':   ['vowel', 'open-mid', 'back', 'unrounded'],
'AO':   ['vowel', 'open-mid', 'back', 'rounded'],
'AW':   ['vowel', 'diphthong', 'open', 'near-close', 'back', 'near-back', 'unrounded', 'rounded'],
'AY':   ['vowel','diphthong','open','near-close','front','near-front','unrounded'],
'EH':   ['vowel', 'open-mid', 'front', 'unrounded'],
'ER':   ['vowel', 'open-mid', 'central', 'unrounded', 'rhotic'],
'EY':   ['vowel', 'diphthong', 'close-mid', 'close', 'front', 'unrounded'],
'IH':   ['vowel', 'near-close', 'near-front', 'unrounded'],
'IY':   ['vowel', 'close', 'front', 'unrounded'],
'OW':   ['vowel', 'close-mid', 'back', 'rounded'],
'OY':   ['vowel', 'diphthong', 'open-mid', 'near-close', 'back', 'near-front', 'rounded', 'unrounded'],
'UH':   ['vowel', 'near-close', 'back', 'rounded'],
'UW':   ['vowel', 'close', 'back', 'rounded'],
'B':    ['consonant', 'stop', 'voiced', 'bilabial'],
'CH':   ['consonant', 'affricate', 'unvoiced', 'alveopalatal'],
'D':    ['consonant', 'stop', 'voiced', 'alveolar'],
'DH':   ['consonant', 'fricative', 'voiced', 'dental'],
'F':    ['consonant', 'fricative', 'unvoiced', 'labiodental'],
'G':    ['consonant', 'stop', 'voiced', 'velar'],
'HH':   ['consonant', 'fricative', 'unvoiced', 'glottal'],
'JH':   ['consonant', 'affricate', 'voiced', 'postalveolar'],
'K':    ['consonant', 'stop', 'unvoiced', 'velar'],
'L':    ['consonant', 'semivowel', 'liquid', 'lateral', 'voiced', 'dental', 'alveolar', 'postalveolar'],
'M':    ['consonant', 'nasal', 'bilabial'],
'N':    ['consonant', 'nasal', 'dental', 'alveolar', 'postalveolar'],
'NG':   ['consonant', 'nasal', 'velar'],
'P':    ['consonant', 'stop', 'unvoiced', 'bilabial'],
'R':    ['consonant', 'semivowel', 'liquid', 'voiced', 'postalveolar', 'rhotic'],
'S':    ['consonant', 'fricative', 'unvoiced', 'alveolar'],
'SH':   ['consonant', 'fricative', 'unvoiced', 'postalveolar'],
'T':    ['consonant', 'stop', 'unvoiced', 'dental', 'alveolar', 'postalveolar'],
'TH':   ['consonant', 'fricative', 'unvoiced', 'dental'],
'V':    ['consonant', 'fricative', 'voiced', 'labiodental'],
'W':    ['consonant', 'semivowel', 'glide', 'voiced', 'labiovelar'],
'Y':    ['consonant', 'semivowel', 'glide', 'voiced', 'palatal'],
'Z':    ['consonant', 'fricative', 'voiced', 'alveolar'],
'ZH':   ['consonant', 'fricative', 'voiced', 'postalveolar']
}

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
#                FEATURE VARIABLE LISTS                     #
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#

phoneme_types = ['consonant',           #No particular order
                 'vowel']
consonants_manners = ['stop',           #No particular order
                      'affricate',
                      'fricative',
                      'liquid',
                      'glide',
                      'lateral',
                      'rhotic',
                      'nasal']
consonants_voices = ['voiced',          #No particular order
                     'unvoiced']
consonants_places = ['bilabial',        #Organized from front to back
                     'labiodental',
                     'dental',
                     'labiovelar',
                     'alveolar',
                     'postalveolar',
                     'alveopalatal',
                     'palatal',
                     'velar',
                     'glottal']
vowels_heights = ['open',               #Organized from open to close
                  'near-open',
                  'open-mid',
                  'mid',
                  'close-mid',
                  'near-close',
                  'close']
vowels_depths = ['front',               #Organized from front to back
                 'near-front',
                 'central',
                 'near-back',
                 'back']
vowels_shapes = ['rounded',             #No particular order
                 'unrounded']
